# Generated by Django 3.2.4 on 2021-06-27 21:04

import OnlineExamination.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50, verbose_name='Название')),
                ('no_of_ques', models.CharField(max_length=20, verbose_name='Всего вопросов')),
                ('total_marks', models.CharField(max_length=20, verbose_name='Максимальная оценка')),
                ('exam_desc', models.TextField(verbose_name='Описание')),
                ('test_link', models.TextField(verbose_name='Ссылка на тест')),
                ('exam_img', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('time_duration', models.DurationField(default='00:00:00', verbose_name='Время на тестирование')),
                ('book_name', models.TextField(verbose_name='Название')),
                ('book_src', models.FileField(upload_to='document/', verbose_name='PDF файл')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Неверно введен телефон!', regex='^\\+?1?\\d{9,12}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=OnlineExamination.models.upload_image, verbose_name='Изображение', width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адресс')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('question', models.TextField(max_length=500)),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
                ('option_three', models.CharField(max_length=100)),
                ('option_four', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.exams')),
            ],
        ),
    ]
